version: '3.8'

networks:
  demo:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql-1
    ports:
      - "3306:3306"
    environment:
      - TZ=${TZ}
      - MYSQL_PASSWORD=123456        
      - MYSQL_ROOT_PASSWORD=123456   
    volumes:
      - ${DATA_PATH_HOST}/mysql_new:/var/lib/mysql
    networks:
      - demo


  etcd:
    image: rancher/coreos-etcd:v3.4.16-rancher1
    container_name: etcd-1
    environment:
      - TZ=${TZ}
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:2379
    ports: 
      - "2379:2379"
      #networks:
      #- backend
    volumes:
      - ${DATA_PATH_HOST}/etcd:/data  
    networks:
      - demo
  
  domtok-jaeger:
    container_name: domtok-jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "6831:6831"
      - "4317:4317"
    networks:
      - demo