version: '3.8'

networks:
  demo:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql-1
    ports:
      - "3306:3306"
    environment:
      - TZ=${TZ}
      - MYSQL_PASSWORD=123456        
      - MYSQL_ROOT_PASSWORD=123456   
    volumes:
      - ${DATA_PATH_HOST}/mysql_new:/var/lib/mysql
    networks:
      - demo


  etcd:
    image: rancher/coreos-etcd:v3.4.16-rancher1
    container_name: etcd-1
    environment:
      - TZ=${TZ}
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:2379
    ports: 
      - "2379:2379"
      #networks:
      #- backend
    volumes:
      - ${DATA_PATH_HOST}/etcd:/data  
    networks:
      - demo
  
  domtok-jaeger:
    container_name: domtok-jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "6831:6831"
      - "4317:4317"
    networks:
      - demo
  
   
  
  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: es_container
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ${DATA_PATH_HOST}/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - demo
  
  
  kibana:
    image: kibana:8.17.0
    container_name: kb_container
    environment:
      # 6. 修正 Kibana，指向两个服务名
      - ELASTICSEARCH_HOSTS=["http://es_container:9200"]
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch # 7. 修正 depends_on
    networks:
      - demo
    
  filebeat:
    image: elastic/filebeat:8.17.0
    container_name: todo-filebeat
    user: root
    command: filebeat -e -E "strict.perms=false"
    volumes:
      - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml # 挂载配置文件
      - ${DATA_PATH_HOST}/filebeat:/usr/share/filebeat/data  # 持久化注册表文件
      - ./pkg/logger/logs:/usr/share/filebeat/logs  # 挂载日志目录
    depends_on:
      - elasticsearch
    restart: on-failure
    networks:
      - demo