server:
  user:
    name: user
    address: localhost:20001
  
  todo:
    name: todo
    address: localhost:20002
    

mysql:
  host: localhost
  port: 3306
  user: root
  password: 123456
  db1: user
  db2: todo
  charset: utf8mb4

etcd:
  endpoints:
    - localhost:2379

jaeger:
  address: localhost:6831

jwt:
  secret: Mao-Meng